export default {
    1: {
        title: 'Frontend Developer',
        summary: 'Looking for freshers at firstsalary.com',
        company_details: 'We at FirstSalary.com, are looking for passionate and enthusiastic people who have a keen interest in working in cutting edge technology and are willing to solve the problem of matching qualified candidates with job opportunities. Basically to assist qualified and competitive candidates get their first salary. We are a small, scrappy, empowered team whose work is critical, visible, and valued. We value autonomy, creativity, curiosity, kindness, and a sense of humor',
        job_details_header: 'We are looking for an experienced developer to immediately contribute to our existing product and help us build new features as well as maintain existing ones.',
        bullet_points: ['We are offering paid internships and looking for candidates who are fluent with Node.js and React.js technologies','Experience working with React.js and Node.js is preferred','Experience working with AWS cloud is preferred'],
        job_details_footer: 'Freshers or last year engineering students are also encouraged to apply. This is a WFH/Remote position. For more information please follow https://twitter.com/firstsalary',
        city: 'Bangalore',
        country: 'India',
        type: 'Full Time',
        posted: 20211024,
        image: 'https://assets.maccarianagency.com/backgrounds/img8.jpg'
    },
    2: {
        title: 'Backend Developer',
        summary: 'Looking for freshers at firstsalary.com as a backend developer',
        company_details: 'We at FirstSalary.com, are looking for passionate and enthusiastic people who have a keen interest in working in cutting edge technology and are willing to solve the problem of matching qualified candidates with job opportunities. Basically to assist qualified and competitive candidates get their first salary. We are a small, scrappy, empowered team whose work is critical, visible, and valued. We value autonomy, creativity, curiosity, kindness, and a sense of humor',
        job_details_header: 'We are looking for an experienced developer to immediately contribute to our existing product and help us build new features as well as maintain existing ones.',
        bullet_points: ['We are offering paid internships and looking for candidates who are fluent with Node.js and React.js technologies','Experience working with React.js and Node.js is preferred','Experience working with AWS cloud is preferred'],
        job_details_footer: 'Freshers or last year engineering students are also encouraged to apply. This is a WFH/Remote position. For more information please follow https://twitter.com/firstsalary',
        city: 'Bangalore',
        country: 'India',
        type: 'Full Time',
        posted: 20211024,
        image: 'https://assets.maccarianagency.com/backgrounds/img9.jpg'
    },
    3: {
        title: 'Senior Database Engineer',
        summary: 'Looking for senior engineer at firstsalary.com as a senior database engineer',
        company_details: 'We at FirstSalary.com, are looking for passionate and enthusiastic people who have a keen interest in working in cutting edge technology and are willing to solve the problem of matching qualified candidates with job opportunities. Basically to assist qualified and competitive candidates get their first salary. We are a small, scrappy, empowered team whose work is critical, visible, and valued. We value autonomy, creativity, curiosity, kindness, and a sense of humor',
        job_details_header: 'We are looking for an experienced developer to immediately contribute to our existing product and help us build new features as well as maintain existing ones.',
        bullet_points: ['We are offering paid internships and looking for candidates who are fluent with Node.js and React.js technologies','Experience working with React.js and Node.js is preferred','Experience working with AWS cloud is preferred'],
        job_details_footer: 'Freshers or last year engineering students are also encouraged to apply. This is a WFH/Remote position. For more information please follow https://twitter.com/firstsalary',
        city: 'Bangalore',
        country: 'India',
        type: 'Full Time',
        posted: 20211024,
        image: 'https://assets.maccarianagency.com/backgrounds/img12.jpg'
    },
    4: {
        title: 'Senior DevOps Engineer',
        summary: 'Looking for senior engineer at firstsalary.com in DevOps role',
        company_details: 'We at FirstSalary.com, are looking for passionate and enthusiastic people who have a keen interest in working in cutting edge technology and are willing to solve the problem of matching qualified candidates with job opportunities. Basically to assist qualified and competitive candidates get their first salary. We are a small, scrappy, empowered team whose work is critical, visible, and valued. We value autonomy, creativity, curiosity, kindness, and a sense of humor',
        job_details_header: 'We are looking for an experienced developer to immediately contribute to our existing product and help us build new features as well as maintain existing ones.',
        bullet_points: ['We are offering paid internships and looking for candidates who are fluent with Node.js and React.js technologies','Experience working with React.js and Node.js is preferred','Experience working with AWS cloud is preferred'],
        job_details_footer: 'Freshers or last year engineering students are also encouraged to apply. This is a WFH/Remote position. For more information please follow https://twitter.com/firstsalary',
        city: 'Bangalore',
        country: 'India',
        type: 'Full Time',
        posted: 20211024,
        image: 'https://assets.maccarianagency.com/backgrounds/img11.jpg'
    },
    5: {
        title: 'Content Writer',
        summary: 'Looking for content writer at firstsalary.com',
        company_details: 'We at FirstSalary.com, are looking for passionate and enthusiastic people who have a keen interest in working in cutting edge technology and are willing to solve the problem of matching qualified candidates with job opportunities. Basically to assist qualified and competitive candidates get their first salary. We are a small, scrappy, empowered team whose work is critical, visible, and valued. We value autonomy, creativity, curiosity, kindness, and a sense of humor',
        job_details_header: 'We are looking for an experienced developer to immediately contribute to our existing product and help us build new features as well as maintain existing ones.',
        bullet_points: ['We are offering paid internships and looking for candidates who are fluent with Node.js and React.js technologies','Experience working with React.js and Node.js is preferred','Experience working with AWS cloud is preferred'],
        job_details_footer: 'Freshers or last year engineering students are also encouraged to apply. This is a WFH/Remote position. For more information please follow https://twitter.com/firstsalary',
        city: 'Bangalore',
        country: 'India',
        type: 'Full Time',
        posted: 20211024,
        image: 'https://assets.maccarianagency.com/backgrounds/img11.jpg'
    },
    6: {
        title: 'Database Engineer',
        summary: 'Looking for database engineer at firstsalary.com',
        company_details: 'We at FirstSalary.com, are looking for passionate and enthusiastic people who have a keen interest in working in cutting edge technology and are willing to solve the problem of matching qualified candidates with job opportunities. Basically to assist qualified and competitive candidates get their first salary. We are a small, scrappy, empowered team whose work is critical, visible, and valued. We value autonomy, creativity, curiosity, kindness, and a sense of humor',
        job_details_header: 'We are looking for an experienced developer to immediately contribute to our existing product and help us build new features as well as maintain existing ones.',
        bullet_points: ['We are offering paid internships and looking for candidates who are fluent with Node.js and React.js technologies','Experience working with React.js and Node.js is preferred','Experience working with AWS cloud is preferred'],
        job_details_footer: 'Freshers or last year engineering students are also encouraged to apply. This is a WFH/Remote position. For more information please follow https://twitter.com/firstsalary',
        city: 'Bangalore',
        country: 'India',
        type: 'Full Time',
        posted: 20211024,
        image: 'https://assets.maccarianagency.com/backgrounds/img9.jpg'
    },
    7: {
        title: 'Full stack developer',
        summary: 'Looking for full stack developer at firstsalary.com',
        company_details: 'We at FirstSalary.com, are looking for passionate and enthusiastic people who have a keen interest in working in cutting edge technology and are willing to solve the problem of matching qualified candidates with job opportunities. Basically to assist qualified and competitive candidates get their first salary. We are a small, scrappy, empowered team whose work is critical, visible, and valued. We value autonomy, creativity, curiosity, kindness, and a sense of humor',
        job_details_header: 'We are looking for an experienced developer to immediately contribute to our existing product and help us build new features as well as maintain existing ones.',
        bullet_points: ['We are offering paid internships and looking for candidates who are fluent with Node.js and React.js technologies','Experience working with React.js and Node.js is preferred','Experience working with AWS cloud is preferred'],
        job_details_footer: 'Freshers or last year engineering students are also encouraged to apply. This is a WFH/Remote position. For more information please follow https://twitter.com/firstsalary',
        city: 'Bangalore',
        country: 'India',
        type: 'Full Time',
        posted: 20211024,
        image: 'https://assets.maccarianagency.com/backgrounds/img11.jpg'
    },
    8: {
        title: 'Site Reliability Engineer',
        summary: 'Looking for SRE engineer at firstsalary.com',
        company_details: 'We at FirstSalary.com, are looking for passionate and enthusiastic people who have a keen interest in working in cutting edge technology and are willing to solve the problem of matching qualified candidates with job opportunities. Basically to assist qualified and competitive candidates get their first salary. We are a small, scrappy, empowered team whose work is critical, visible, and valued. We value autonomy, creativity, curiosity, kindness, and a sense of humor',
        bullet_points: ['We are offering paid internships and looking for candidates who are fluent with Node.js and React.js technologies','Experience working with React.js and Node.js is preferred','Experience working with AWS cloud is preferred'],
        job_details_footer: 'Freshers or last year engineering students are also encouraged to apply. This is a WFH/Remote position. For more information please follow https://twitter.com/firstsalary',
        city: 'Bangalore',
        country: 'India',
        type: 'Full Time',
        posted: 20211024,
        image: 'https://assets.maccarianagency.com/backgrounds/img12.jpg'
    },
    9: {
        title: 'Full stack developer',
        summary: 'Looking for full stack developer at firstsalary.com',
        company_details: 'We at FirstSalary.com, are looking for passionate and enthusiastic people who have a keen interest in working in cutting edge technology and are willing to solve the problem of matching qualified candidates with job opportunities. Basically to assist qualified and competitive candidates get their first salary!',
        job_details_header: 'We are looking for an experienced developer to immediately contribute to our existing product and help us build new features as well as maintain existing ones.',
        bullet_points: ['We are offering paid internships and looking for candidates who are fluent with Node.js and React.js technologies','Experience working with React.js and Node.js is preferred','Experience working with AWS cloud is preferred'],
        job_details_footer: 'Freshers or last year engineering students are also encouraged to apply. This is a WFH/Remote position. For more information please follow https://twitter.com/firstsalary',
        city: 'Bangalore',
        country: 'India',
        type: 'Full Time',
        posted: 20211024,
        image: 'https://assets.maccarianagency.com/backgrounds/img9.jpg'
    },
    10: {
        title: 'UI/UX Developer',
        summary: 'Looking for UI/UX designer at firstsalary.com',
        company_details: 'We at FirstSalary.com, are looking for passionate and enthusiastic people who have a keen interest in working in cutting edge technology and are willing to solve the problem of matching qualified candidates with job opportunities. Basically to assist qualified and competitive candidates get their first salary!',
        job_details_header: 'We are looking for an experienced developer to immediately contribute to our existing product and help us build new features as well as maintain existing ones.',
        bullet_points: ['We are offering paid internships and looking for candidates who are fluent with Node.js and React.js technologies','Experience working with React.js and Node.js is preferred','Experience working with AWS cloud is preferred'],
        job_details_footer: 'Freshers or last year engineering students are also encouraged to apply. This is a WFH/Remote position. For more information please follow https://twitter.com/firstsalary',
        city: 'Bangalore',
        country: 'India',
        type: 'Full Time',
        posted: 20211024,
        image: 'https://assets.maccarianagency.com/backgrounds/img11.jpg'
    },
    11: {
        title: 'iOS Developer',
        summary: 'Looking for mobile engineer at firstsalary.com',
        company_details: 'We at FirstSalary.com, are looking for passionate and enthusiastic people who have a keen interest in working in cutting edge technology and are willing to solve the problem of matching qualified candidates with job opportunities. Basically to assist qualified and competitive candidates get their first salary!',
        job_details_header: 'We are looking for an experienced developer to immediately contribute to our existing product and help us build new features as well as maintain existing ones.',
        bullet_points: ['We are offering paid internships and looking for candidates who are fluent with Node.js and React.js technologies','Experience working with React.js and Node.js is preferred','Experience working with AWS cloud is preferred'],
        job_details_footer: 'Freshers or last year engineering students are also encouraged to apply. This is a WFH/Remote position. For more information please follow https://twitter.com/firstsalary',
        city: 'Bangalore',
        country: 'India',
        type: 'Full Time',
        posted: 20211024,
        image: 'https://assets.maccarianagency.com/backgrounds/img12.jpg'
    },
    12: {
        title: 'Site Reliability Engineer',
        summary: 'Looking for SRE engineer at firstsalary.com',
        company_details: 'We at FirstSalary.com, are looking for passionate and enthusiastic people who have a keen interest in working in cutting edge technology and are willing to solve the problem of matching qualified candidates with job opportunities. Basically to assist qualified and competitive candidates get their first salary. We are a small, scrappy, empowered team whose work is critical, visible, and valued. We value autonomy, creativity, curiosity, kindness, and a sense of humor',
        job_details_header: 'We are looking for an experienced developer to immediately contribute to our existing product and help us build new features as well as maintain existing ones.',
        bullet_points: ['We are offering paid internships and looking for candidates who are fluent with Node.js and React.js technologies','Experience working with React.js and Node.js is preferred','Experience working with AWS cloud is preferred'],
        job_details_footer: 'Freshers or last year engineering students are also encouraged to apply. This is a WFH/Remote position. For more information please follow https://twitter.com/firstsalary',
        city: 'Bangalore',
        country: 'India',
        type: 'Full Time',
        posted: 20211024,
        image: 'https://assets.maccarianagency.com/backgrounds/img11.jpg'
    },
    13: {
        title: 'Android Developer',
        summary: 'Looking for Android developer at firstsalary.com',
        company_details: 'We at FirstSalary.com, are looking for passionate and enthusiastic people who have a keen interest in working in cutting edge technology and are willing to solve the problem of matching qualified candidates with job opportunities. Basically to assist qualified and competitive candidates get their first salary!',
        job_details_header: 'We are looking for an experienced developer to immediately contribute to our existing product and help us build new features as well as maintain existing ones.',
        bullet_points: ['We are offering paid internships and looking for candidates who are fluent with Node.js and React.js technologies','Experience working with React.js and Node.js is preferred','Experience working with AWS cloud is preferred'],
        job_details_footer: 'Freshers or last year engineering students are also encouraged to apply. This is a WFH/Remote position. For more information please follow https://twitter.com/firstsalary',
        city: 'Bangalore',
        country: 'India',
        type: 'Full Time',
        posted: 20211024,
        image: 'https://assets.maccarianagency.com/backgrounds/img11.jpg'
    },
    14: {
        title: 'Javascript Developer',
        summary: 'Looking for java script developer at firstsalary.com',
        company_details: 'We at FirstSalary.com, are looking for passionate and enthusiastic people who have a keen interest in working in cutting edge technology and are willing to solve the problem of matching qualified candidates with job opportunities. Basically to assist qualified and competitive candidates get their first salary. We are a small, scrappy, empowered team whose work is critical, visible, and valued. We value autonomy, creativity, curiosity, kindness, and a sense of humor',
        job_details_header: 'We are looking for an experienced developer to immediately contribute to our existing product and help us build new features as well as maintain existing ones.',
        bullet_points: ['We are offering paid internships and looking for candidates who are fluent with Node.js and React.js technologies','Experience working with React.js and Node.js is preferred','Experience working with AWS cloud is preferred'],
        job_details_footer: 'Freshers or last year engineering students are also encouraged to apply. This is a WFH/Remote position. For more information please follow https://twitter.com/firstsalary',
        city: 'Bangalore',
        country: 'India',
        type: 'Full Time',
        posted: 20211024,
        image: 'https://assets.maccarianagency.com/backgrounds/img12.jpg'
    },
    15: {
        title: 'Node js Developer',
        summary: 'Looking for Node JS developer at firstsalary.com',
        company_details: 'We at FirstSalary.com, are looking for passionate and enthusiastic people who have a keen interest in working in cutting edge technology and are willing to solve the problem of matching qualified candidates with job opportunities. Basically to assist qualified and competitive candidates get their first salary!',
        job_details_header: 'We are looking for an experienced developer to immediately contribute to our existing product and help us build new features as well as maintain existing ones.',
        bullet_points: ['We are offering paid internships and looking for candidates who are fluent with Node.js and React.js technologies','Experience working with React.js and Node.js is preferred','Experience working with AWS cloud is preferred'],
        job_details_footer: 'Freshers or last year engineering students are also encouraged to apply. This is a WFH/Remote position. For more information please follow https://twitter.com/firstsalary',
        city: 'Bangalore',
        country: 'India',
        type: 'Full Time',
        posted: 20211024,
        image: 'https://assets.maccarianagency.com/backgrounds/img9.jpg'
    },
    16: {
        title: 'React js Developer',
        summary: 'Looking for React JS developer at firstsalary.com',
        company_details: 'We at FirstSalary.com, are looking for passionate and enthusiastic people who have a keen interest in working in cutting edge technology and are willing to solve the problem of matching qualified candidates with job opportunities. Basically to assist qualified and competitive candidates get their first salary!',
        job_details_header: 'We are looking for an experienced developer to immediately contribute to our existing product and help us build new features as well as maintain existing ones.',
        bullet_points: ['We are offering paid internships and looking for candidates who are fluent with Node.js and React.js technologies','Experience working with React.js and Node.js is preferred','Experience working with AWS cloud is preferred'],
        job_details_footer: 'Freshers or last year engineering students are also encouraged to apply. This is a WFH/Remote position. For more information please follow https://twitter.com/firstsalary',
        city: 'Bangalore',
        country: 'India',
        type: 'Full Time',
        posted: 20211024,
        image: 'https://assets.maccarianagency.com/backgrounds/img8.jpg'
    }
}
