name: CI

on:
  pull_request:
 
env: 
  NODE_VERSION: 16

jobs: 
  build:
    name: Build Artefacts 
    runs-on: ubuntu-latest
    steps: 
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0 

      - name: Delete old Artifacts
        run:  rm -rf build.zip || true
     
      - name: Install Dependencies
        run:  yarn install
        
      - name: Build Artefacts
        run:  yarn run build

      - name: Install Zip
        run:  sudo apt install zip

      - name: Zip Build Artefacts
        run:  zip -r build.zip build && pwd && ls
    
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add build.zip || true
          git commit -m "Add changes" -a || true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.pull_request.head.ref }}
